# Generated by Django 5.1.6 on 2025-02-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_mentorassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='usn',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
